### ISSUE TITLE
Proton_opt.py test failed 

### ISSUE THREAD

**Issue by ybfu** [CurtisColwell/StrainViz#46]
Hello, I am a beginner in Python code and recently I wanted to calculate the strain force for a cyclophane compound using the StrainViz code. But I met some problems in the beginning. 

I use the Gaussian 16 on the HPC, therefore I changed the g09 by g16 in the StrainViz.bash script. Then I loaded the Gaussian/16.C.01 and Anaconda3 in the slurm and requested 48 CPUs for my node. I also upload the StrainViz package to my home folder and keep everything unchanged. Then I want to test the example molecule and used the command: 

bash StrainViz.bash example-molecule 48 "M062X/6-31G(d)"

There was an error happened:
Traceback (most recent call last):
  File "/home/h5/yfu/StrainViz-master/scripts/proton_opt.py", line 47, in <module>
    create_protonopts(geometry_filename, file, level)
  File "/home/h5/yfu/StrainViz-master/scripts/proton_opt.py", line 12, in create_protonopts
    dummy_geometry = load_geometry(dummy)
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/h5/yfu/StrainViz-master/scripts/scripts.py", line 52, in load_geometry
    output_lines = open(geometry,'r').read().splitlines()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 108] Cannot send after transport endpoint shutdown

In the StrainViz-master/input/example-molecule/ I can see some dummy2_protonopt.inp or dummy5_protonopt.inp files created but not all 5 files are created. It seems that proton_opt.py doesn't work well. Then I tried to use the test files in the scripts folder. The command is:  bash test.bash test 48
However, there was an error: 
Proton_opt.py test failed.
cp: cannot stat 'scripts/tests/test_dummy_protonopt.out': No such file or directory

So what kind of problem will cause such results? Thank you in advance.

**Comment by janavath21-sonu** [comment]
Hi,
Can help me with stranviz sofyware i am also having  same problem
@ybfu

**Comment by Lalitharavichandran** [comment]
I am also facing the same error. Did you solve it?

**Comment by CurtisColwell** [comment]
Hi, I can't actively maintain this anymore, but if this is the example that comes with the software my best guess is that you're having a dependency issue. Reverting to python packages that are from ~2019 might help. If you keep having issues, reach out to the Jasti lab. They should still be actively using StrainViz.
